import { useEffect, useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { api } from '../../api';
import type { ChecklistItem, Dashboard } from '../../domain';
import './preparation.css';

export function ChecklistPage(){const [items,setItems]=useState<ChecklistItem[]>([]);const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [editing,setEditing]=useState<ChecklistItem|'new'|null>(null);const load=async()=>{const [i,d]=await Promise.all([api.checklist(),api.dashboard()]);setItems(i);setDashboard(d);};useEffect(()=>{void load();},[]);return <section className="prepPage"><header><div><small>TRIP CHECKLIST</small><h1>함께 준비하기</h1><p>담당자와 마감일을 정하고 준비 상황을 맞춰보세요.</p></div><button className="primary" onClick={()=>setEditing('new')}><Plus/>항목 추가</button></header><div className="collabChecklist">{items.map((item)=><article className={item.is_completed?'done':''} key={item.id}><input type="checkbox" checked={Boolean(item.is_completed)} onChange={async(e)=>{await api.update('checklist',item.id,{is_completed:e.target.checked?1:0});await load();}}/><div><small>{item.category}</small><h3>{item.title}</h3>{item.notes&&<p>{item.notes}</p>}<footer><span>{item.assignee_name??'담당자 미정'}</span><time>{item.due_date??'마감일 없음'}</time></footer></div><aside><button onClick={()=>setEditing(item)} aria-label="수정"><Pencil/></button><button onClick={async()=>{if(confirm('준비 항목을 삭제할까요?')){await api.remove('checklist',item.id);await load();}}} aria-label="삭제"><Trash2/></button></aside></article>)}</div>{!items.length&&<div className="prepEmpty"><b>아직 준비 항목이 없어요.</b><span>함께 챙길 첫 항목을 추가해 보세요.</span></div>}{editing&&dashboard&&<ChecklistEditor item={editing==='new'?null:editing} dashboard={dashboard} close={()=>setEditing(null)} saved={async()=>{setEditing(null);await load();}}/>}</section>;}

function ChecklistEditor({item,dashboard,close,saved}:{item:ChecklistItem|null;dashboard:Dashboard;close:()=>void;saved:()=>void}){const [error,setError]=useState('');const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const x=Object.fromEntries(new FormData(event.currentTarget));const data={title:x.title,category:x.category,assignee_id:x.assignee_id?Number(x.assignee_id):null,due_date:x.due_date||null,notes:x.notes||null,...(!item?{is_completed:0}:{})};try{if(item)await api.update('checklist',item.id,data);else await api.create('checklist',data);await saved();}catch(reason){setError(reason instanceof Error?reason.message:'저장하지 못했어요.');}};return <div className="backdrop" onMouseDown={close}><section className="modal" onMouseDown={(e)=>e.stopPropagation()}><header><h2>{item?'준비 항목 수정':'준비 항목 추가'}</h2><button onClick={close}>×</button></header><form onSubmit={submit}><label>할 일<input name="title" defaultValue={item?.title} required/></label><div className="formRow"><label>담당자<select name="assignee_id" defaultValue={item?.assignee_id??''}><option value="">미정</option>{dashboard.members.map((member)=><option value={member.id} key={member.id}>{member.name}</option>)}</select></label><label>카테고리<select name="category" defaultValue={item?.category??'예약'}><option>예약</option><option>준비물</option><option>통신</option><option>금융</option><option>기타</option></select></label></div><label>마감일<input name="due_date" type="date" defaultValue={item?.due_date??''}/></label><label>메모<textarea name="notes" rows={3} defaultValue={item?.notes??''}/></label>{error&&<p className="errorText">{error}</p>}<button className="primary">저장</button></form></section></div>;}
