import { useEffect, useState } from 'react';
import { ExternalLink, FileText, Pencil, Plus, Trash2 } from 'lucide-react';
import { api } from '../../api';
import type { Reservation } from '../../domain';
import { boardApi } from '../board/boardApi';
import './preparation.css';

type AvailableAttachment = { id: number; file_name: string; content_type: string; byte_size: number; post_title: string | null };

export function ReservationsPage() {
  const [items,setItems]=useState<Reservation[]>([]);const [attachments,setAttachments]=useState<AvailableAttachment[]>([]);const [editing,setEditing]=useState<Reservation|'new'|null>(null);const [error,setError]=useState('');
  const load=async()=>{try{const [r,a]=await Promise.all([api.reservations(),api.availableAttachments()]);setItems(r);setAttachments(a);setError('');}catch(reason){setError(reason instanceof Error?reason.message:'예약 정보를 불러오지 못했어요.');}};useEffect(()=>{void load();},[]);
  return <section className="prepPage"><header><div><small>RESERVATIONS & INFO</small><h1>예약과 여행 정보</h1><p>확인서와 이용 시간을 한곳에서 빠르게 확인하세요.</p></div><button className="primary" onClick={()=>setEditing('new')}><Plus/>예약 추가</button></header><aside className="privacyNote">카드번호, 여권번호, 비밀번호 등 민감정보는 저장하지 마세요.</aside>{error&&<p className="errorText">{error}</p>}
    <div className="reservationList">{items.map((item)=><article key={item.id}><div className="reservationDate"><b>{item.start_at?.slice(0,10)??item.reservation_date??'날짜 미정'}</b><small>{item.start_at?.slice(11)||''}{item.end_at&&` — ${item.end_at.replace('T',' ')}`}</small></div><div className="reservationBody"><small>{item.type}</small><h2>{item.title}</h2>{item.notes&&<p>{item.notes}</p>}<footer>{item.link&&<a href={item.link} target="_blank" rel="noreferrer"><ExternalLink/>관련 링크</a>}{item.attachments.map((file)=><a href={boardApi.attachmentUrl(file.id)} target="_blank" rel="noreferrer" key={file.id}><FileText/>{file.file_name}</a>)}</footer></div><div className="quietActions"><button onClick={()=>setEditing(item)} aria-label="수정"><Pencil/></button><button onClick={async()=>{if(confirm('예약 정보를 삭제할까요?')){await api.remove('reservations',item.id);await load();}}} aria-label="삭제"><Trash2/></button></div></article>)}</div>{!items.length&&<div className="prepEmpty"><b>저장된 예약이 없어요.</b><span>숙소, 항공, 투어 확인서를 Board 자료와 연결해 보세요.</span></div>}
    {editing&&<ReservationEditor item={editing==='new'?null:editing} available={attachments} close={()=>setEditing(null)} saved={async()=>{setEditing(null);await load();}}/>}
  </section>;
}

function ReservationEditor({item,available,close,saved}:{item:Reservation|null;available:AvailableAttachment[];close:()=>void;saved:()=>void}){const [selected,setSelected]=useState(item?.attachments.map((file)=>file.id)??[]);const [error,setError]=useState('');const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const x=Object.fromEntries(new FormData(event.currentTarget));const data={title:x.title,type:x.type,start_at:x.start_at||null,end_at:x.end_at||null,reservation_date:x.start_at?String(x.start_at).slice(0,10):null,confirmation_number:x.confirmation_number||null,link:x.link||null,notes:x.notes||null,attachment_ids:selected};try{if(item)await api.update('reservations',item.id,data);else await api.create('reservations',data);await saved();}catch(reason){setError(reason instanceof Error?reason.message:'저장하지 못했어요.');}};return <div className="backdrop" onMouseDown={close}><section className="modal reservationEditor" onMouseDown={(e)=>e.stopPropagation()}><header><div><small>{item?'예약 편집':'새 예약'}</small><h2>{item?.title??'예약 정보 추가'}</h2></div><button onClick={close}>×</button></header><form onSubmit={submit}><label>이름<input name="title" defaultValue={item?.title} required autoFocus/></label><label>종류<select name="type" defaultValue={item?.type??'숙소'}><option>숙소</option><option>항공</option><option>투어</option><option>교통</option><option>티켓</option><option>기타</option></select></label><div className="formRow"><label>시작<input name="start_at" type="datetime-local" defaultValue={item?.start_at??''}/></label><label>종료<input name="end_at" type="datetime-local" defaultValue={item?.end_at??''}/></label></div><label>예약번호<input name="confirmation_number" defaultValue={item?.confirmation_number??''}/></label><label>관련 링크<input name="link" type="url" defaultValue={item?.link??''}/></label><label>메모<textarea name="notes" rows={3} defaultValue={item?.notes??''}/></label><fieldset><legend>Board 확인서 연결</legend>{available.length?available.map((file)=><label className="attachmentChoice" key={file.id}><input type="checkbox" checked={selected.includes(file.id)} onChange={(e)=>setSelected(e.target.checked?[...selected,file.id]:selected.filter((id)=>id!==file.id))}/><FileText/><span><b>{file.file_name}</b><small>{file.post_title??'Board 첨부'}</small></span></label>):<p>Board에 올린 이미지나 PDF가 아직 없어요.</p>}</fieldset><p className="sensitiveWarning">민감한 결제·신분증 정보는 입력하지 마세요.</p>{error&&<p className="errorText">{error}</p>}<button className="primary">저장</button></form></section></div>;}
