import { useState, type FormEvent } from 'react';
import { ArrowRight, Inbox, Link, MapPin, Plus, Trash2, X } from 'lucide-react';
import { api } from '../../api';
import type { Place, PlanningItem } from '../../domain';

const types = ['관광', '식사', '카페', '쇼핑', '이동', '기타'];
const formatDay = (date: string) => new Intl.DateTimeFormat('ko-KR', { month: 'numeric', day: 'numeric', weekday: 'short' }).format(new Date(`${date}T00:00:00`));

export function PlanningInbox({ items, places, dates, reloadPlanning, reloadSchedule }: { items: PlanningItem[]; places: Place[]; dates: string[]; reloadPlanning: () => void; reloadSchedule: () => void }) {
  const inbox = items.filter((item) => item.status === 'inbox'); const [adding, setAdding] = useState(false); const [scheduling, setScheduling] = useState<PlanningItem>();
  return <aside className="planningInbox"><header><div><small>PLANNING INBOX</small><h3><Inbox />일정 후보 <em>{inbox.length}</em></h3></div><button onClick={() => setAdding(true)}><Plus />추가</button></header><p>날짜를 정하지 않은 아이디어를 모아두세요.</p><div>{inbox.map((item) => <article key={item.id}><small>{item.item_type} · {item.created_by_name}</small><b>{item.title}</b>{item.place_name && <span><MapPin />{item.place_name}</span>}{item.url && <a href={item.url} target="_blank"><Link />링크 열기</a>}<footer><button onClick={async()=>{if(confirm('이 후보를 삭제할까요?')){await api.remove('planning',item.id);reloadPlanning();}}}><Trash2 />삭제</button><button className="placeCandidate" onClick={() => setScheduling(item)}>DAY에 넣기<ArrowRight /></button></footer></article>)}{!inbox.length && <button className="emptyInbox" onClick={() => setAdding(true)}><Plus />떠오른 장소나 활동을 저장해 보세요.</button>}</div>{adding && <PlanningEditor places={places} close={()=>setAdding(false)} done={reloadPlanning} />}{scheduling && <ScheduleCandidate item={scheduling} dates={dates} close={()=>setScheduling(undefined)} done={()=>{reloadPlanning();reloadSchedule();}} />}</aside>;
}

function Dialog({children,close}:{children:React.ReactNode;close:()=>void}){return <div className="backdrop" onMouseDown={close}><section className="modal planningModal" onMouseDown={(e)=>e.stopPropagation()}>{children}</section></div>}
function PlanningEditor({places,close,done}:{places:Place[];close:()=>void;done:()=>void}){
 const [error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));try{await api.create('planning',{...v,place_id:v.place_id?Number(v.place_id):null,url:v.url||null,notes:v.notes||null});close();done();}catch(reason){setError(reason instanceof Error?reason.message:'저장하지 못했습니다.')}};
 return <Dialog close={close}><header><div><small>날짜 미정 아이디어</small><h2>후보 추가</h2></div><button type="button" onClick={close}><X /></button></header><form onSubmit={submit}><label>제목<input name="title" required autoFocus /></label><div className="formRow"><label>유형<select name="item_type">{types.map(type=><option key={type}>{type}</option>)}</select></label><label>장소<select name="place_id"><option value="">장소 미정</option>{places.map(place=><option value={place.id} key={place.id}>{place.name}</option>)}</select></label></div><label>관련 URL<input name="url" type="url" placeholder="https://" /></label><label>메모<textarea name="notes" rows={3} /></label>{error&&<p className="errorText">{error}</p>}<button type="submit" className="primary">Inbox에 저장</button></form></Dialog>;
}
function ScheduleCandidate({item,dates,close,done}:{item:PlanningItem;dates:string[];close:()=>void;done:()=>void}){
 const [error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));try{await api.schedulePlanning(item.id,{day_date:v.day_date,start_time:v.start_time||null,end_time:v.end_time||null});close();done();}catch(reason){setError(reason instanceof Error?reason.message:'전환하지 못했습니다.')}};
 return <Dialog close={close}><header><div><small>일정 후보로 전환</small><h2>{item.title}</h2></div><button type="button" onClick={close}><X /></button></header><p>날짜에 배치한 뒤에도 확정 전 후보로 표시돼요.</p><form onSubmit={submit}><label>날짜<select name="day_date">{dates.map((date,index)=><option value={date} key={date}>DAY {index+1} · {formatDay(date)}</option>)}</select></label><div className="formRow"><label>시작<input name="start_time" type="time" /></label><label>종료<input name="end_time" type="time" /></label></div>{error&&<p className="errorText">{error}</p>}<button type="submit" className="primary">DAY에 후보로 배치</button></form></Dialog>;
}
