import { useState, type FormEvent, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { ArrowRight, ChevronDown, Inbox, Link, Plus, Trash2, X } from 'lucide-react';
import { api } from '../../api';
import type { PlanningItem } from '../../domain';

const types = ['관광', '식사', '카페', '쇼핑', '이동', '기타'];
const formatDay = (date: string) => new Intl.DateTimeFormat('ko-KR', { month: 'numeric', day: 'numeric', weekday: 'short' }).format(new Date(`${date}T00:00:00`));

export function PlanningInbox({ items, dates, reloadPlanning, reloadSchedule }: { items: PlanningItem[]; dates: string[]; reloadPlanning: () => void; reloadSchedule: () => void }) {
  const inbox = items.filter((item) => item.status === 'inbox'); const [open, setOpen] = useState(false); const [adding, setAdding] = useState(false); const [scheduling, setScheduling] = useState<PlanningItem>();
  return <aside className={`planningInbox ${open ? 'open' : ''}`}><header><button className="planningToggle" onClick={() => setOpen(!open)}><Inbox /><span><b>날짜를 정하지 않은 후보</b><small>{inbox.length}개</small></span><ChevronDown /></button><button onClick={() => setAdding(true)}><Plus />추가</button></header>{open && <div className="planningBody">{inbox.map((item) => <article key={item.id}><small>{item.item_type} · {item.created_by_name}</small><b>{item.title}</b>{item.url && <a href={item.url} target="_blank" rel="noreferrer"><Link />링크 열기</a>}<footer><button onClick={async () => { if (confirm('이 후보를 삭제할까요?')) { await api.remove('planning', item.id); reloadPlanning(); } }}><Trash2 />삭제</button><button className="placeCandidate" onClick={() => setScheduling(item)}>DAY에 넣기<ArrowRight /></button></footer></article>)}{!inbox.length && <button className="emptyInbox" onClick={() => setAdding(true)}><Plus />떠오른 장소나 활동을 저장해 보세요.</button>}</div>}{adding && <PlanningEditor close={() => setAdding(false)} done={reloadPlanning} />}{scheduling && <ScheduleCandidate item={scheduling} dates={dates} close={() => setScheduling(undefined)} done={() => { reloadPlanning(); reloadSchedule(); }} />}</aside>;
}

function Dialog({ children, close }: { children: ReactNode; close: () => void }) { return createPortal(<div className="backdrop" onMouseDown={close}><section className="modal planningModal" onMouseDown={(event) => event.stopPropagation()}>{children}</section></div>, document.body); }
function PlanningEditor({ close, done }: { close: () => void; done: () => void }) {
  const [error, setError] = useState(''); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await api.create('planning', { ...values, place_id: null, url: values.url || null, notes: values.notes || null }); close(); done(); } catch (reason) { setError(reason instanceof Error ? reason.message : '저장하지 못했습니다.'); } };
  return <Dialog close={close}><header><div><h2>후보 추가</h2></div><button type="button" onClick={close}><X /></button></header><form onSubmit={submit}><label>제목<input name="title" required autoFocus /></label><label>유형<select name="item_type">{types.map((type) => <option key={type}>{type}</option>)}</select></label><label>관련 URL<input name="url" type="url" placeholder="https://" /></label><label>메모<textarea name="notes" rows={3} /></label>{error && <p className="errorText">{error}</p>}<button type="submit" className="primary">후보로 저장</button></form></Dialog>;
}
function ScheduleCandidate({ item, dates, close, done }: { item: PlanningItem; dates: string[]; close: () => void; done: () => void }) {
  const [error, setError] = useState(''); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await api.schedulePlanning(item.id, { day_date: values.day_date, start_time: values.start_time || null, end_time: values.end_time || null }); close(); done(); } catch (reason) { setError(reason instanceof Error ? reason.message : '일정으로 옮기지 못했습니다.'); } };
  return <Dialog close={close}><header><div><h2>{item.title}</h2></div><button type="button" onClick={close}><X /></button></header><p>날짜를 정하면 일정 후보로 표시돼요.</p><form onSubmit={submit}><label>날짜<select name="day_date">{dates.map((date, index) => <option value={date} key={date}>DAY {index + 1} · {formatDay(date)}</option>)}</select></label><div className="formRow"><label>시작<input name="start_time" type="time" /></label><label>종료<input name="end_time" type="time" /></label></div>{error && <p className="errorText">{error}</p>}<button type="submit" className="primary">DAY에 배치</button></form></Dialog>;
}
