import { useEffect, useMemo, useState, type CSSProperties, type FormEvent } from 'react';
import { CalendarDays, Clock3, ExternalLink, Link, MapPin, Pencil, Plus, Trash2, X } from 'lucide-react';
import { api } from '../../api';
import { useTrip } from '../../app/TripContext';
import type { PlanningItem, ScheduleItem } from '../../domain';
import { PlanningInbox } from './PlanningInbox';
import './schedule-polish.css';
import './schedule-time.css';

const categories = ['관광', '이동', '숙소', '식사', '카페', '쇼핑', '기타'];
const dayMs = 86_400_000; const toDate = (value: string) => new Date(`${value}T00:00:00`);
const isoDate = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const formatDay = (date: string) => new Intl.DateTimeFormat('ko-KR', { month: 'numeric', day: 'numeric', weekday: 'short' }).format(toDate(date));
const tripDates = (start: string, end: string) => Array.from({ length: Math.round((toDate(end).getTime() - toDate(start).getTime()) / dayMs) + 1 }, (_, index) => isoDate(new Date(toDate(start).getTime() + index * dayMs)));
const minutes = (time: string | null, fallback: number) => time ? Number(time.slice(0, 2)) * 60 + Number(time.slice(3)) : fallback;
const categoryClass = (category: string) => `tone${Math.abs([...category].reduce((sum, char) => sum + char.charCodeAt(0), 0)) % 5}`;
const hours = Array.from({ length: 24 }, (_, index) => String(index).padStart(2, '0'));
const minuteSteps = Array.from({ length: 12 }, (_, index) => String(index * 5).padStart(2, '0'));
type Draft = { item?: ScheduleItem; dayDate: string; startTime?: string };
type TimelineItem = { item: ScheduleItem; startTime: string | null; endTime: string | null; continuation: boolean };

export function SchedulePage() {
  const trip = useTrip(); const [items, setItems] = useState<ScheduleItem[]>(); const [planning, setPlanning] = useState<PlanningItem[]>(); const [error, setError] = useState('');
  const reloadSchedule = () => { void api.schedule().then(setItems).catch((reason: Error) => setError(reason.message)); }; const reloadPlanning = () => { void api.planning().then(setPlanning).catch((reason: Error) => setError(reason.message)); };
  useEffect(() => { let active = true; Promise.all([api.schedule(), api.planning()]).then(([nextItems, nextPlanning]) => { if (active) { setItems(nextItems); setPlanning(nextPlanning); } }).catch((reason: Error) => { if (active) setError(reason.message); }); return () => { active = false; }; }, []);
  if (error) return <div className="state">{error}<button onClick={() => window.location.reload()}>다시 시도</button></div>;
  if (!items || !planning) return <div className="state">일정을 불러오는 중…</div>;
  return <ScheduleWorkspace dates={tripDates(trip.start_date, trip.end_date)} items={items} planning={planning} reload={reloadSchedule} reloadPlanning={reloadPlanning} />;
}

function ScheduleWorkspace({ dates, items, planning, reload, reloadPlanning }: { dates: string[]; items: ScheduleItem[]; planning: PlanningItem[]; reload: () => void; reloadPlanning: () => void }) {
  const [selectedDate, setSelectedDate] = useState(dates[0]); const [draft, setDraft] = useState<Draft>(); const [selectedItem, setSelectedItem] = useState<ScheduleItem>();
  const grouped = useMemo(() => Object.fromEntries(dates.map((date, index) => { const current = items.filter((item) => item.day_date === date).map((item): TimelineItem => ({ item, startTime: item.start_time, endTime: item.end_next_day ? '24:00' : item.end_time, continuation: false })); const previousDate = dates[index - 1]; const continued = previousDate ? items.filter((item) => item.day_date === previousDate && Boolean(item.end_next_day) && item.end_time).map((item): TimelineItem => ({ item, startTime: '00:00', endTime: item.end_time, continuation: true })) : []; return [date, [...continued, ...current].sort((a, b) => (a.startTime ?? '99:99').localeCompare(b.startTime ?? '99:99'))]; })), [dates, items]);
  const timelineStart = items.some((item) => Boolean(item.end_next_day)) ? 0 : 7; const timelineHours = 24 - timelineStart;
  const openSlot = (date: string, hour = 9) => setDraft({ dayDate: date, startTime: `${String(hour).padStart(2, '0')}:00` });
  return <section className="scheduleWorkspace"><header className="scheduleHeader"><div><h2>여행 일정</h2><p>날짜별 일정을 한눈에 보고 빠르게 계획하세요.</p></div><button className="scheduleAdd" onClick={() => openSlot(selectedDate)}><Plus size={18} />일정 추가</button></header>
    <nav className="mobileDayTabs" aria-label="여행 날짜">{dates.map((date, index) => <button key={date} className={date === selectedDate ? 'active' : ''} onClick={() => setSelectedDate(date)}><b>DAY {index + 1}</b><span>{formatDay(date)}</span></button>)}</nav>
    <div className="scheduleDesktopLayout"><div className="desktopItinerary" style={{ '--days': dates.length, '--hours': timelineHours, '--hour': '48px' } as CSSProperties}><div className="itineraryHeader"><span />{dates.map((date, index) => <button key={date} onClick={() => { setSelectedDate(date); openSlot(date); }}><b>DAY {index + 1}</b><span>{formatDay(date)}</span><em>{grouped[date].length}개 일정</em></button>)}</div><div className="itineraryBody"><aside>{Array.from({ length: timelineHours }, (_, index) => <time key={index}>{String(index + timelineStart).padStart(2, '0')}:00</time>)}</aside>{dates.map((date) => <DayColumn key={date} items={grouped[date]} timelineStart={timelineStart} timelineHours={timelineHours} open={(hour) => openSlot(date, hour)} show={setSelectedItem} />)}</div></div><PlanningInbox items={planning} dates={dates} reloadPlanning={reloadPlanning} reloadSchedule={reload} /></div>
    <div className="mobileTimeline">{grouped[selectedDate].length ? grouped[selectedDate].map((entry, index) => <MobileItem key={`${entry.item.id}-${entry.continuation ? 'next' : index}`} entry={entry} show={() => setSelectedItem(entry.item)} />) : <button className="emptyDay" onClick={() => openSlot(selectedDate)}><Plus />아직 일정이 없어요. 첫 일정을 추가해 보세요.</button>}<button className="floatingAdd" onClick={() => openSlot(selectedDate)} aria-label="일정 추가"><Plus /></button></div>
    {selectedItem && <ScheduleDetails item={selectedItem} close={() => setSelectedItem(undefined)} edit={() => { setSelectedItem(undefined); setDraft({ item: selectedItem, dayDate: selectedItem.day_date }); }} />}
    {draft && <ScheduleEditor draft={draft} dates={dates} close={() => setDraft(undefined)} reload={reload} />}
  </section>;
}

function DayColumn({ items, timelineStart, timelineHours, open, show }: { items: TimelineItem[]; timelineStart: number; timelineHours: number; open: (hour: number) => void; show: (item: ScheduleItem) => void }) { const hourHeight = 48; return <section className="dayColumn">{Array.from({ length: timelineHours }, (_, index) => <button key={index} className="timeSlot" onClick={() => open(index + timelineStart)} aria-label={`${index + timelineStart}시 일정 추가`} />)}{items.map((entry) => { const start = minutes(entry.startTime, timelineStart * 60); const end = entry.endTime === '24:00' ? 1440 : minutes(entry.endTime, start + 60); const top = (start - timelineStart * 60) / 60 * hourHeight; const height = Math.max(42, (end - start) / 60 * hourHeight); return <button key={`${entry.item.id}-${entry.continuation ? 'next' : 'start'}`} className={`scheduleBlock ${categoryClass(entry.item.category)} ${entry.item.status === 'candidate' ? 'candidate' : ''} ${entry.continuation ? 'continued' : ''}`} style={{ top, height }} onClick={() => show(entry.item)}><small>{entry.continuation ? '전날부터 · ' : ''}{entry.item.category}{entry.item.status === 'candidate' ? ' · 후보' : ''}</small><b>{entry.item.title}</b><time>{entry.startTime ?? '시간 미정'}{entry.endTime && ` – ${entry.endTime}`}</time>{entry.item.place_name && <span><MapPin />{entry.item.place_name}</span>}</button>; })}</section>; }
function MobileItem({ entry, show }: { entry: TimelineItem; show: () => void }) { return <article className="mobileScheduleItem"><time>{entry.startTime ?? '미정'}</time><i /><button className={categoryClass(entry.item.category)} onClick={show}><small>{entry.continuation ? '전날부터 · ' : ''}{entry.item.category}{entry.item.status === 'candidate' ? ' · 후보' : ''}</small><b>{entry.item.title}</b><span><Clock3 />{entry.startTime ?? '시간 미정'}{entry.endTime && ` – ${entry.endTime}`}</span>{entry.item.place_name && <span><MapPin />{entry.item.place_name}</span>}</button></article>; }

function ScheduleDetails({ item, close, edit }: { item: ScheduleItem; close: () => void; edit: () => void }) { return <div className="backdrop" onMouseDown={close}><section className="modal scheduleDetails" onMouseDown={(event) => event.stopPropagation()}><header><div><small>{item.category}{item.status === 'candidate' ? ' · 후보' : ''}</small><h2>{item.title}</h2></div><button onClick={close} aria-label="닫기"><X /></button></header><div className="detailRows"><p><CalendarDays /><span><b>{formatDay(item.day_date)}</b><small>{item.day_date}</small></span></p><p><Clock3 /><span><b>{item.start_time ?? '시간 미정'}{item.end_time && ` – ${item.end_time}${item.end_next_day ? ' (다음날)' : ''}`}</b></span></p>{item.place_name && <p><MapPin /><span><b>{item.place_name}</b></span></p>}{item.notes && <p className="detailNotes">{item.notes}</p>}</div><footer>{item.url && <a href={item.url} target="_blank" rel="noreferrer"><ExternalLink />링크 열기</a>}<button className="primary" onClick={edit}><Pencil />수정</button></footer></section></div>; }

function TimeSelect({ name, label, value }: { name: string; label: string; value?: string | null }) { const [hour, setHour] = useState(value?.slice(0, 2) ?? ''); const [minute, setMinute] = useState(value?.slice(3, 5) ?? '00'); return <label>{label}<span className="timeParts"><select value={hour} onChange={(event) => setHour(event.target.value)} aria-label={`${label} 시`}><option value="">--시</option>{hours.map((entry) => <option key={entry}>{entry}</option>)}</select><b>:</b><select value={minute} onChange={(event) => setMinute(event.target.value)} disabled={!hour} aria-label={`${label} 분`}>{minuteSteps.map((entry) => <option key={entry}>{entry}</option>)}</select></span><input type="hidden" name={name} value={hour ? `${hour}:${minute}` : ''} /></label>; }
function ScheduleEditor({ draft, dates, close, reload }: { draft: Draft; dates: string[]; close: () => void; reload: () => void }) {
  const item = draft.item; const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); const startTime = String(values.start_time || ''); const endTime = String(values.end_time || ''); const payload = { title: values.title, day_date: values.day_date, start_time: startTime || null, end_time: endTime || null, end_next_day: Boolean(startTime && endTime && endTime < startTime), place_id: item?.place_id ?? null, category: values.category, notes: values.notes || null, url: values.url || null, status: values.status, ...(item ? { sort_order: item.sort_order } : {}) }; try { if (item) await api.update('schedule', item.id, payload); else await api.create('schedule', payload); close(); reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : '저장하지 못했습니다.'); setSaving(false); } };
  return <div className="backdrop" onMouseDown={close}><section className="modal scheduleEditor" onMouseDown={(event) => event.stopPropagation()}><header><h2>{item ? '일정 수정' : '일정 추가'}</h2><button onClick={close} aria-label="닫기"><X /></button></header><form onSubmit={submit}><label>제목<input name="title" defaultValue={item?.title} required autoFocus /></label><div className="formRow"><label>날짜<select name="day_date" defaultValue={item?.day_date ?? draft.dayDate}>{dates.map((date, index) => <option value={date} key={date}>DAY {index + 1} · {formatDay(date)}</option>)}</select></label><label>상태<select name="status" defaultValue={item?.status ?? 'confirmed'}><option value="confirmed">확정</option><option value="candidate">후보</option></select></label></div><div className="formRow timeRow"><TimeSelect name="start_time" label="시작" value={item?.start_time ?? draft.startTime} /><TimeSelect name="end_time" label="종료" value={item?.end_time} /></div><label>카테고리<select name="category" defaultValue={item?.category ?? '관광'}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label>{item?.place_name && <p className="legacyPlace"><MapPin />{item.place_name}</p>}<label><Link />관련 URL<input name="url" type="url" defaultValue={item?.url ?? ''} placeholder="https://" /></label><label>메모<textarea name="notes" defaultValue={item?.notes ?? ''} rows={2} /></label>{error && <p className="errorText">{error}</p>}<footer>{item && <button type="button" className="editorDelete" onClick={async () => { if (confirm('이 일정을 삭제할까요?')) { await api.remove('schedule', item.id); close(); reload(); } }}><Trash2 />삭제</button>}<button className="primary" disabled={saving}>{saving ? '저장 중…' : '저장'}</button></footer></form></section></div>;
}
