import { useEffect, useMemo, useState } from 'react';
import { CalendarPlus, ExternalLink, Filter, MapPinned, Plus, Trash2, X } from 'lucide-react';
import { api } from '../../api';
import type { Dashboard, Place, PlanningItem, ScheduleItem } from '../../domain';
import { MapCanvas } from './MapCanvas';
import './map.css';

type FilterName = 'all' | 'must' | 'scheduled' | 'candidate';

export function MapPage() {
  const [places, setPlaces] = useState<Place[]>([]); const [schedule, setSchedule] = useState<ScheduleItem[]>([]);
  const [planning, setPlanning] = useState<PlanningItem[]>([]); const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [filter, setFilter] = useState<FilterName>('all'); const [category, setCategory] = useState('전체');
  const [selectedId, setSelectedId] = useState<number | null>(null); const [editing, setEditing] = useState<Place | 'new' | null>(null);
  const [schedulePlace, setSchedulePlace] = useState<Place | null>(null); const [error, setError] = useState('');
  const load = async () => { try { const [p, s, pi, d] = await Promise.all([api.places(), api.schedule(), api.planning(), api.dashboard()]); setPlaces(p); setSchedule(s); setPlanning(pi); setDashboard(d); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : '장소를 불러오지 못했어요.'); } };
  useEffect(() => { void load(); }, []);
  const scheduledIds = useMemo(() => new Set(schedule.map((item) => item.place_id).filter(Boolean)), [schedule]);
  const candidateIds = useMemo(() => new Set(planning.filter((item) => item.status === 'inbox').map((item) => item.place_id).filter(Boolean)), [planning]);
  const categories = ['전체', ...new Set(places.map((place) => place.category))];
  const visible = places.filter((place) => (category === '전체' || place.category === category) && (filter === 'all' || filter === 'must' && place.is_must_visit === 1 || filter === 'scheduled' && scheduledIds.has(place.id) || filter === 'candidate' && candidateIds.has(place.id)));
  const selected = visible.find((place) => place.id === selectedId) ?? null;
  return <section className="mapPage"><header><div><small>PLACES MAP</small><h1>가고 싶은 장소</h1><p>지도와 목록을 함께 보며 일정에 바로 연결하세요.</p></div><button className="primary" onClick={() => setEditing('new')}><Plus />장소 추가</button></header>
    <nav className="placeFilters"><Filter size={16} />{([['all','전체'],['must','꼭 가기'],['scheduled','일정 포함'],['candidate','후보']] as const).map(([id,label]) => <button className={filter === id ? 'active' : ''} onClick={() => setFilter(id)} key={id}>{label}</button>)}<select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></nav>
    {error && <p className="mapError">{error}</p>}<div className="mapLayout"><div className="mapStage"><MapCanvas places={visible} selectedId={selectedId} select={setSelectedId} />{selected && <PlacePopup place={selected} scheduled={scheduledIds.has(selected.id)} close={() => setSelectedId(null)} edit={() => setEditing(selected)} addSchedule={() => setSchedulePlace(selected)} />}</div><div className="placeList">{visible.map((place) => <PlaceCard place={place} selected={selectedId === place.id} scheduled={scheduledIds.has(place.id)} candidate={candidateIds.has(place.id)} select={() => setSelectedId(place.id)} edit={() => setEditing(place)} addSchedule={() => setSchedulePlace(place)} remove={async () => { if (confirm('장소를 삭제할까요?')) { await api.remove('places', place.id); await load(); } }} key={place.id} />)}{!visible.length && <p>조건에 맞는 장소가 없어요.</p>}</div></div>
    {editing && <PlaceForm place={editing === 'new' ? null : editing} close={() => setEditing(null)} saved={async () => { setEditing(null); await load(); }} />}{schedulePlace && dashboard && <SchedulePlace place={schedulePlace} dashboard={dashboard} close={() => setSchedulePlace(null)} saved={async () => { setSchedulePlace(null); await load(); }} />}
  </section>;
}

function PlaceCard({ place, selected, scheduled, candidate, select, edit, addSchedule, remove }: { place: Place; selected: boolean; scheduled: boolean; candidate: boolean; select: () => void; edit: () => void; addSchedule: () => void; remove: () => void }) { const mapUrl = place.map_url ?? (place.latitude != null ? `https://www.openstreetmap.org/?mlat=${place.latitude}&mlon=${place.longitude}#map=16/${place.latitude}/${place.longitude}` : null); return <article className={`placeMapCard ${selected ? 'selected' : ''}`} onClick={select}>{place.photo_url ? <img src={place.photo_url} alt="" /> : <i><MapPinned /></i>}<div><small>{place.category}{place.is_must_visit ? ' · 꼭 가기' : ''}</small><h3>{place.name}</h3><p>{place.address ?? '주소 미입력'}</p><aside>{scheduled && <em>일정 포함</em>}{candidate && <em>후보</em>}</aside><footer>{mapUrl && <a href={mapUrl} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()}><ExternalLink />지도 열기</a>}<button onClick={(event) => { event.stopPropagation(); addSchedule(); }}><CalendarPlus />일정 추가</button><button onClick={(event) => { event.stopPropagation(); edit(); }}>수정</button><button onClick={(event) => { event.stopPropagation(); remove(); }}><Trash2 /></button></footer></div></article>; }
function PlacePopup({ place, scheduled, close, edit, addSchedule }: { place: Place; scheduled: boolean; close: () => void; edit: () => void; addSchedule: () => void }) { return <aside className="mapPopup"><button onClick={close}><X /></button><small>{place.category}</small><b>{place.name}</b><span>{place.address}</span>{scheduled && <em>일정에 포함됨</em>}<footer><button onClick={edit}>수정</button><button className="primary" onClick={addSchedule}>일정 추가</button></footer></aside>; }

function PlaceForm({ place, close, saved }: { place: Place | null; close: () => void; saved: () => void }) { const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const x = Object.fromEntries(new FormData(event.currentTarget)); const data = { name:x.name,category:x.category,address:x.address||null,map_url:x.map_url||null,website_url:x.website_url||null,photo_url:x.photo_url||null,latitude:x.latitude?Number(x.latitude):null,longitude:x.longitude?Number(x.longitude):null,notes:x.notes||null,is_must_visit:x.is_must_visit?1:0 }; if(place) await api.update('places',place.id,data); else await api.create('places',data); await saved(); }; return <div className="backdrop" onMouseDown={close}><section className="modal" onMouseDown={(e)=>e.stopPropagation()}><header><h2>{place?'장소 수정':'장소 추가'}</h2><button onClick={close}>×</button></header><form onSubmit={submit}><label>이름<input name="name" defaultValue={place?.name} required /></label><label>카테고리<select name="category" defaultValue={place?.category}><option>관광</option><option>맛집</option><option>카페</option><option>쇼핑</option><option>숙소</option><option>기타</option></select></label><label>주소<input name="address" defaultValue={place?.address??''} /></label><div className="coordinateFields"><label>위도<input name="latitude" type="number" step="any" min="-90" max="90" defaultValue={place?.latitude??''} /></label><label>경도<input name="longitude" type="number" step="any" min="-180" max="180" defaultValue={place?.longitude??''} /></label></div><label>사진 URL<input name="photo_url" type="url" defaultValue={place?.photo_url??''} /></label><label>웹사이트 URL<input name="website_url" type="url" defaultValue={place?.website_url??''} /></label><label>지도 URL<input name="map_url" type="url" defaultValue={place?.map_url??''} /></label><label className="check"><input name="is_must_visit" type="checkbox" defaultChecked={Boolean(place?.is_must_visit)} />꼭 가기</label><button className="primary">저장</button></form></section></div>; }
function SchedulePlace({ place, dashboard, close, saved }: { place: Place; dashboard: Dashboard; close: () => void; saved: () => void }) { const days:string[]=[]; const date=new Date(`${dashboard.trip.start_date}T00:00:00Z`); const end=new Date(`${dashboard.trip.end_date}T00:00:00Z`); while(date<=end){days.push(date.toISOString().slice(0,10));date.setUTCDate(date.getUTCDate()+1);} const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const x=Object.fromEntries(new FormData(event.currentTarget));await api.create('schedule',{title:place.name,day_date:x.day_date,start_time:x.start_time||null,end_time:null,place_id:place.id,category:place.category,notes:place.notes,url:place.website_url,status:'confirmed',participant_ids:[]});await saved();}; return <div className="backdrop" onMouseDown={close}><section className="modal" onMouseDown={(e)=>e.stopPropagation()}><header><h2>{place.name} 일정 추가</h2><button onClick={close}>×</button></header><form onSubmit={submit}><label>날짜<select name="day_date">{days.map((day)=><option key={day}>{day}</option>)}</select></label><label>시작 시간<input name="start_time" type="time" /></label><button className="primary">일정에 추가</button></form></section></div>; }
