import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ExternalLink, FileText, Image, MapPinned, MessageCircle, Pencil, Plus, Send, SlidersHorizontal, Trash2, X } from 'lucide-react';
import { UserAvatar } from '../../components/UserAvatar';
import { boardApi, type BoardPost } from './boardApi';
import './board.css';
import './board-polish.css';
import './board-attachments.css';

const formatBytes = (bytes: number) => bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)}KB` : `${(bytes / 1024 / 1024).toFixed(1)}MB`;
const kindLabel = (kind: BoardPost['kind']) => ({ general: '일반', place: '장소', restaurant: '맛집', cafe: '카페', tour: '투어', info: '예약/정보' })[kind];
const isMapLink = (value: string) => { try { const parsed = new URL(value); const host = parsed.hostname.toLowerCase(); return host.includes('google.') && parsed.pathname.startsWith('/maps') || host === 'maps.app.goo.gl' || host === 'maps.google.com' || host === 'goo.gl' && parsed.pathname.startsWith('/maps'); } catch { return false; } };

function FilePreview({ file, remove }: { file: File; remove: () => void }) {
  const [src, setSrc] = useState('');
  useEffect(() => { if (!file.type.startsWith('image/')) return; const next = URL.createObjectURL(file); setSrc(next); return () => URL.revokeObjectURL(next); }, [file]);
  return <span className="pendingFile">{src ? <img src={src} alt="" /> : <FileText />}<small>{file.name}</small><button type="button" onClick={remove} aria-label={`${file.name} 제거`}><X /></button></span>;
}

export function BoardPage() {
  const [posts, setPosts] = useState<BoardPost[]>([]); const [page, setPage] = useState(1); const [hasMore, setHasMore] = useState(false); const [usage, setUsage] = useState(0); const [currentUserId, setCurrentUserId] = useState(0);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [kind, setKind] = useState('general'); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [url, setUrl] = useState(''); const [files, setFiles] = useState<File[]>([]); const [expanded, setExpanded] = useState(false);
  const [publishing, setPublishing] = useState(false); const [busyPost, setBusyPost] = useState<number>(); const inputRef = useRef<HTMLInputElement>(null);
  const load = async (nextPage = 1, append = false) => { try { setLoading(true); const result = await boardApi.posts(nextPage); setPosts((current) => append ? [...current, ...result.posts] : result.posts); setPage(nextPage); setHasMore(result.has_more); setUsage(result.usage_bytes); setCurrentUserId(result.current_user_id); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : '게시물을 불러오지 못했어요.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { const paste = (event: ClipboardEvent) => { const images = Array.from(event.clipboardData?.items ?? []).filter((item) => item.kind === 'file' && item.type.startsWith('image/')).map((item, index) => { const file = item.getAsFile(); return file ? new File([file], `clipboard-${Date.now()}-${index + 1}.${file.type.split('/')[1] || 'png'}`, { type: file.type }) : null; }).filter((file): file is File => Boolean(file)); if (images.length) { event.preventDefault(); setFiles((current) => [...current, ...images]); } }; window.addEventListener('paste', paste); return () => window.removeEventListener('paste', paste); }, []);
  const publish = async (event: FormEvent) => { event.preventDefault(); if (publishing) return; try { setPublishing(true); setError(''); await boardApi.createPost({ kind, title, content, url, files }); setKind('general'); setTitle(''); setContent(''); setUrl(''); setFiles([]); setExpanded(false); if (inputRef.current) inputRef.current.value = ''; await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : '게시물을 저장하지 못했어요.'); } finally { setPublishing(false); } };
  const convert = async (post: BoardPost) => { try { setBusyPost(post.id); setError(''); await boardApi.convertPost(post.id, 'planning'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : '일정 후보로 추가하지 못했어요.'); } finally { setBusyPost(undefined); } };
  const updatePost = (id: number, change: (post: BoardPost) => BoardPost) => setPosts((current) => current.map((post) => post.id === id ? change(post) : post));
  return <section className="boardPage">
    <header className="boardHeader"><div><h1>여행 보드</h1><p>가고 싶은 곳, 맛집, 예약 정보와 링크를 함께 모아보세요.</p></div>{usage >= 1.4 * 1024 ** 3 && <aside><b>저장공간을 많이 사용하고 있어요</b><span><i style={{ width: `${Math.min(100, usage / (2 * 1024 ** 3) * 100)}%` }} /></span><small>{formatBytes(usage)} 사용 중</small></aside>}</header>
    <form className={`postComposer ${expanded ? 'expanded' : ''}`} onSubmit={publish}><textarea value={content} onChange={(event) => { setContent(event.target.value); if (event.target.value) setExpanded(true); }} placeholder="여행 정보를 공유해보세요…" />{expanded && <><div className="composerMeta"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="제목 (선택)" /><select value={kind} onChange={(event) => setKind(event.target.value)} aria-label="카테고리"><option value="general">일반</option><option value="place">장소</option><option value="restaurant">맛집</option><option value="cafe">카페</option><option value="tour">투어</option><option value="info">예약/정보</option></select></div><input className="composerLink" type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="링크 (선택)" /></>}{files.length > 0 && <div className="pendingFiles">{files.map((file, index) => <FilePreview key={`${file.name}-${file.lastModified}-${index}`} file={file} remove={() => setFiles((current) => current.filter((_, fileIndex) => fileIndex !== index))} />)}</div>}<footer><label><Plus size={16} />사진/파일<input ref={inputRef} type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(event) => { const selected = Array.from(event.target.files ?? []); setFiles((current) => [...current, ...selected]); setExpanded(true); event.target.value = ''; }} /></label><button type="button" className="composerOptions" onClick={() => setExpanded((value) => !value)}><SlidersHorizontal size={15} />옵션</button><span>{files.length ? `${files.length}개 첨부` : 'Ctrl+V 이미지 붙여넣기'}</span><button className="primary" disabled={publishing}><Send size={16} />{publishing ? '게시 중…' : '게시'}</button></footer></form>
    {error && <p className="boardError">{error}</p>}
    <div className="postFeed">{posts.map((post) => <PostCard key={post.id} post={post} currentUserId={currentUserId} busy={busyPost === post.id} setBusy={setBusyPost} reload={() => load()} update={(change) => updatePost(post.id, change)} setError={setError} convert={() => convert(post)} />)}</div>
    {!loading && posts.length === 0 && <div className="boardEmpty"><Image /><b>아직 공유한 자료가 없어요.</b><span>첫 링크나 파일을 올려보세요.</span></div>}{hasMore && <button className="loadMore" disabled={loading} onClick={() => load(page + 1, true)}>{loading ? '불러오는 중…' : '이전 게시물 더 보기'}</button>}
  </section>;
}

function PostCard({ post, currentUserId, busy, setBusy, reload, update, setError, convert }: { post: BoardPost; currentUserId: number; busy: boolean; setBusy: (id?: number) => void; reload: () => Promise<void>; update: (change: (post: BoardPost) => BoardPost) => void; setError: (message: string) => void; convert: () => void }) {
  const link = post.map_url ?? post.url; const mapLink = link ? isMapLink(link) : false;
  const [preview, setPreview] = useState<{ src: string; name: string } | null>(null);
  const [editing, setEditing] = useState(false);
  useEffect(() => {
    if (!preview) return;
    const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setPreview(null); };
    document.addEventListener('keydown', close);
    return () => document.removeEventListener('keydown', close);
  }, [preview]);
  return <article className="postCard"><header><UserAvatar user={{ id: post.author_id, name: post.author_name, avatar_color: post.avatar_color, avatar_key: post.avatar_key }} /><div><b>{post.author_name}</b><small>{post.created_at.replace('T', ' ').slice(0, 16)}</small></div>{post.author_id === currentUserId && <><button aria-label="게시물 수정" disabled={busy} onClick={() => setEditing(true)}><Pencil size={16} /></button><button aria-label="게시물 삭제" disabled={busy} onClick={async () => { if (confirm('게시물과 첨부 파일을 삭제할까요?')) try { setBusy(post.id); await boardApi.deletePost(post.id); await reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : '게시물을 삭제하지 못했어요.'); } finally { setBusy(); } }}><Trash2 size={16} /></button></>}</header>
    <small className={`postKind ${post.kind}`}>{kindLabel(post.kind)}</small>{post.title && <h2>{post.title}</h2>}{post.content && <p>{post.content}</p>}{link && <a className={`sharedUrl ${mapLink ? 'mapLink' : ''}`} href={link} target="_blank" rel="noreferrer">{mapLink ? <MapPinned size={15} /> : <ExternalLink size={15} />}{mapLink ? '지도에서 보기' : '링크 열기'}<small>{link}</small></a>}
    {post.attachments.length > 0 && <div className="attachments">{post.attachments.map((attachment) => {
      const attachmentUrl = boardApi.attachmentUrl(attachment.id);
      return attachment.content_type.startsWith('image/') ? <button type="button" className="imageAttachment" onClick={() => setPreview({ src: attachmentUrl, name: attachment.file_name })} key={attachment.id}><img src={attachmentUrl} alt={attachment.file_name} /><small>{attachment.file_name}</small></button> : <a className="pdf" href={attachmentUrl} target="_blank" rel="noreferrer" key={attachment.id}><FileText /><span><b>{attachment.file_name}</b><small>{formatBytes(attachment.byte_size)}</small></span></a>;
    })}</div>}
    {preview && <div className="imagePreviewBackdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setPreview(null); }}><section className="imagePreview" role="dialog" aria-modal="true" aria-label={`${preview.name} 미리보기`}><header><span>{preview.name}</span><button type="button" onClick={() => setPreview(null)} aria-label="이미지 미리보기 닫기"><X /></button></header><img src={preview.src} alt={preview.name} /></section></div>}
    {editing && <EditPostModal post={post} close={() => setEditing(false)} saved={(data) => { update((current) => ({ ...current, ...data, map_url: null })); setEditing(false); }} setError={setError} />}
    <footer><span><MessageCircle size={14} />댓글 {post.comment_count}</span><button disabled={busy || post.conversions.some((item) => item.target_type === 'planning')} onClick={convert}><Plus size={14} />{busy ? '추가 중…' : '일정 후보로 추가'}</button></footer>
    <Comments post={post} currentUserId={currentUserId} update={update} setError={setError} />
  </article>;
}

function EditPostModal({ post, close, saved, setError }: { post: BoardPost; close: () => void; saved: (data: Pick<BoardPost, 'kind' | 'title' | 'content' | 'url' | 'attachments'>) => void; setError: (message: string) => void }) {
  const [kind, setKind] = useState(post.kind); const [title, setTitle] = useState(post.title ?? ''); const [content, setContent] = useState(post.content ?? ''); const [url, setUrl] = useState(post.map_url ?? post.url ?? ''); const [saving, setSaving] = useState(false); const [removed, setRemoved] = useState<Set<number>>(() => new Set()); const [files, setFiles] = useState<File[]>([]);
  const activeAttachments = post.attachments.filter((attachment) => !removed.has(attachment.id));
  useEffect(() => { const paste = (event: ClipboardEvent) => { const images = Array.from(event.clipboardData?.items ?? []).filter((item) => item.kind === 'file' && item.type.startsWith('image/')).map((item, index) => { const file = item.getAsFile(); return file ? new File([file], `clipboard-${Date.now()}-${index + 1}.${file.type.split('/')[1] || 'png'}`, { type: file.type }) : null; }).filter((file): file is File => Boolean(file)); if (images.length) { event.preventDefault(); setFiles((current) => [...current, ...images]); } }; window.addEventListener('paste', paste); return () => window.removeEventListener('paste', paste); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (saving) return; try { setSaving(true); const data = { kind, title: title.trim() || null, content: content.trim() || null, url: url.trim() || null }; const result = await boardApi.replacePost(post.id, { ...data, files, removeAttachmentIds: [...removed] }); saved({ ...data, attachments: result.attachments }); } catch (reason) { setError(reason instanceof Error ? reason.message : '게시물을 수정하지 못했어요.'); } finally { setSaving(false); } };
  return <div className="editPostBackdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><form className="editPostModal" role="dialog" aria-modal="true" aria-label="게시물 수정" onSubmit={submit}><header><h2>게시물 수정</h2><button type="button" onClick={close} aria-label="게시물 수정 닫기"><X /></button></header><label><span>카테고리</span><select value={kind} onChange={(event) => setKind(event.target.value as BoardPost['kind'])}><option value="general">일반</option><option value="place">장소</option><option value="restaurant">맛집</option><option value="cafe">카페</option><option value="tour">투어</option><option value="info">예약/정보</option></select></label><label><span>제목</span><input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={120} placeholder="제목 (선택)" /></label><label><span>내용</span><textarea value={content} onChange={(event) => setContent(event.target.value)} maxLength={5000} placeholder="내용" /></label><label><span>링크</span><input type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://" /></label><section className="editAttachments"><b>사진 / 파일</b>{activeAttachments.length > 0 && <div className="existingAttachments">{activeAttachments.map((attachment) => <span key={attachment.id}>{attachment.content_type.startsWith('image/') ? <img src={boardApi.attachmentUrl(attachment.id)} alt={attachment.file_name} /> : <FileText />}<small>{attachment.file_name}</small><button type="button" onClick={() => setRemoved((current) => new Set(current).add(attachment.id))} aria-label={`${attachment.file_name} 삭제`}><X /></button></span>)}</div>}{files.length > 0 && <div className="pendingFiles">{files.map((file, index) => <FilePreview key={`${file.name}-${file.lastModified}-${index}`} file={file} remove={() => setFiles((current) => current.filter((_, fileIndex) => fileIndex !== index))} />)}</div>}<label className="editFilePicker"><Plus size={16} />사진/파일 추가<input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(event) => { setFiles((current) => [...current, ...Array.from(event.target.files ?? [])]); event.target.value = ''; }} /></label><small>여러 장을 선택하거나 클립보드 이미지를 붙여넣을 수 있어요.</small></section><footer><button type="button" onClick={close}>취소</button><button className="primary" disabled={saving}>{saving ? '저장 중…' : '저장'}</button></footer></form></div>;
}

function Comments({ post, currentUserId, update, setError }: { post: BoardPost; currentUserId: number; update: (change: (post: BoardPost) => BoardPost) => void; setError: (message: string) => void }) {
  const [value, setValue] = useState(''); const [saving, setSaving] = useState(false); const [expanded, setExpanded] = useState(false); const [loading, setLoading] = useState(false); const [deletingCommentIds, setDeletingCommentIds] = useState<Set<number>>(() => new Set());
  const visible = expanded ? post.comments : post.comments.slice(-2); const hiddenCount = Math.max(0, post.comment_count - visible.length);
  const showAll = async () => { if (expanded) { setExpanded(false); return; } try { setLoading(true); const result = await boardApi.comments(post.id); update((current) => ({ ...current, comments: result.comments })); setExpanded(true); } catch (reason) { setError(reason instanceof Error ? reason.message : '댓글을 불러오지 못했어요.'); } finally { setLoading(false); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); const content = value.trim(); if (!content || saving) return; try { setSaving(true); const comment = await boardApi.createComment(post.id, content); update((current) => ({ ...current, comments: [...current.comments, comment], comment_count: current.comment_count + 1 })); setValue(''); } catch (reason) { setError(reason instanceof Error ? reason.message : '댓글을 저장하지 못했어요.'); } finally { setSaving(false); } };
  const remove = async (commentId: number) => { if (deletingCommentIds.has(commentId)) return; setDeletingCommentIds((current) => new Set(current).add(commentId)); update((current) => ({ ...current, comments: current.comments.filter((comment) => comment.id !== commentId), comment_count: Math.max(0, current.comment_count - 1) })); try { await boardApi.deleteComment(post.id, commentId); } catch (reason) { try { const result = await boardApi.comments(post.id); update((current) => ({ ...current, comments: result.comments, comment_count: result.comments.length })); } catch { /* keep the focused delete error */ } setError(reason instanceof Error ? reason.message : '댓글을 삭제하지 못했어요.'); } finally { setDeletingCommentIds((current) => { const next = new Set(current); next.delete(commentId); return next; }); } };
  return <section className="comments"><div className="commentList">{visible.map((comment) => <article key={comment.id}><UserAvatar user={{ id: comment.author_id, name: comment.author_name, avatar_color: comment.avatar_color, avatar_key: comment.avatar_key }} /><span><b>{comment.author_name}</b><p>{comment.content}</p><small>{comment.created_at.replace('T', ' ').slice(0, 16)}</small></span>{comment.author_id === currentUserId && <button aria-label="댓글 삭제" disabled={deletingCommentIds.has(comment.id)} onClick={() => remove(comment.id)}><X /></button>}</article>)}</div>{post.comment_count > 2 && <button className="commentsToggle" disabled={loading} onClick={showAll}>{loading ? '불러오는 중…' : expanded ? '댓글 접기' : `댓글 ${hiddenCount}개 더 보기`}</button>}<form onSubmit={submit}><input value={value} onChange={(event) => setValue(event.target.value)} maxLength={500} placeholder="댓글을 남겨보세요" aria-label="댓글" /><button disabled={saving || !value.trim()}>{saving ? '등록 중…' : '등록'}</button></form></section>;
}
