import { useEffect, useRef, useState } from 'react';
import { ExternalLink, FileText, Image, MapPinned, Plus, Send, SlidersHorizontal, Trash2, X } from 'lucide-react';
import { UserAvatar } from '../../components/UserAvatar';
import { boardApi, type BoardPost } from './boardApi';
import './board.css';
import './board-polish.css';
import './board-attachments.css';

const formatBytes = (bytes: number) => bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)}KB` : `${(bytes / 1024 / 1024).toFixed(1)}MB`;
const kindLabel = (kind: BoardPost['kind']) => ({ general: '일반', place: '장소', restaurant: '맛집', cafe: '카페', tour: '투어', info: '예약/정보' })[kind];
const isMapLink = (value: string) => { try { const parsed = new URL(value); const host = parsed.hostname.toLowerCase(); return host.includes('google.') && parsed.pathname.startsWith('/maps') || host === 'maps.app.goo.gl' || host === 'maps.google.com' || host === 'goo.gl' && parsed.pathname.startsWith('/maps'); } catch { return false; } };
function FilePreview({ file, remove }: { file: File; remove: () => void }) { const [src, setSrc] = useState(''); useEffect(() => { if (!file.type.startsWith('image/')) return; const next = URL.createObjectURL(file); setSrc(next); return () => URL.revokeObjectURL(next); }, [file]); return <span className="pendingFile">{src ? <img src={src} alt="" /> : <FileText />}<small>{file.name}</small><button type="button" onClick={remove} aria-label={`${file.name} 제거`}><X /></button></span>; }

export function BoardPage() {
  const [posts, setPosts] = useState<BoardPost[]>([]); const [page, setPage] = useState(1); const [hasMore, setHasMore] = useState(false); const [usage, setUsage] = useState(0);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [kind, setKind] = useState('general'); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [url, setUrl] = useState(''); const [files, setFiles] = useState<File[]>([]);
  const [expanded, setExpanded] = useState(false);
  const [publishing, setPublishing] = useState(false); const [busyPost, setBusyPost] = useState<number>(); const inputRef = useRef<HTMLInputElement>(null);
  const load = async (nextPage = 1, append = false) => { try { setLoading(true); const result = await boardApi.posts(nextPage); setPosts((current) => append ? [...current, ...result.posts] : result.posts); setPage(nextPage); setHasMore(result.has_more); setUsage(result.usage_bytes); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : '게시물을 불러오지 못했어요.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { const paste = (event: ClipboardEvent) => { const images = Array.from(event.clipboardData?.items ?? []).filter((item) => item.kind === 'file' && item.type.startsWith('image/')).map((item, index) => { const file = item.getAsFile(); return file ? new File([file], `clipboard-${Date.now()}-${index + 1}.${file.type.split('/')[1] || 'png'}`, { type: file.type }) : null; }).filter((file): file is File => Boolean(file)); if (images.length) { event.preventDefault(); setFiles((current) => [...current, ...images]); } }; window.addEventListener('paste', paste); return () => window.removeEventListener('paste', paste); }, []);
  const publish = async (event: React.FormEvent) => { event.preventDefault(); if (publishing) return; try { setPublishing(true); setError(''); await boardApi.createPost({ kind, title, content, url, files }); setKind('general'); setTitle(''); setContent(''); setUrl(''); setFiles([]); setExpanded(false); if (inputRef.current) inputRef.current.value = ''; await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : '게시물을 저장하지 못했어요.'); } finally { setPublishing(false); } };
  const convert = async (post: BoardPost) => { try { setBusyPost(post.id); setError(''); await boardApi.convertPost(post.id, 'planning'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : '일정 후보로 추가하지 못했어요.'); } finally { setBusyPost(undefined); } };
  return <section className="boardPage">
    <header className="boardHeader"><div><h1>여행 보드</h1><p>가고 싶은 곳, 맛집, 예약 정보와 링크를 함께 모아보세요.</p></div>{usage >= 1.4 * 1024 ** 3 && <aside><b>저장공간을 많이 사용하고 있어요</b><span><i style={{ width: `${Math.min(100, usage / (2 * 1024 ** 3) * 100)}%` }} /></span><small>{formatBytes(usage)} 사용 중</small></aside>}</header>
    <form className={`postComposer ${expanded ? 'expanded' : ''}`} onSubmit={publish}><textarea value={content} onChange={(event) => { setContent(event.target.value); if (event.target.value) setExpanded(true); }} placeholder="여행 정보를 공유해보세요…" />{expanded && <><div className="composerMeta"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="제목 (선택)" /><select value={kind} onChange={(event) => setKind(event.target.value)} aria-label="카테고리"><option value="general">일반</option><option value="place">장소</option><option value="restaurant">맛집</option><option value="cafe">카페</option><option value="tour">투어</option><option value="info">예약/정보</option></select></div><input className="composerLink" type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="링크 (선택)" /></>}{files.length > 0 && <div className="pendingFiles">{files.map((file, index) => <FilePreview key={`${file.name}-${file.lastModified}-${index}`} file={file} remove={() => setFiles((current) => current.filter((_, fileIndex) => fileIndex !== index))} />)}</div>}<footer><label><Plus size={16} />사진/파일<input ref={inputRef} type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={(event) => { const selected = Array.from(event.target.files ?? []); setFiles((current) => [...current, ...selected]); setExpanded(true); event.target.value = ''; }} /></label><button type="button" className="composerOptions" onClick={() => setExpanded((value) => !value)}><SlidersHorizontal size={15} />옵션</button><span>{files.length ? `${files.length}개 첨부` : 'Ctrl+V 이미지 붙여넣기'}</span><button className="primary" disabled={publishing}><Send size={16} />{publishing ? '게시 중…' : '게시'}</button></footer></form>
    {error && <p className="boardError">{error}</p>}<div className="postFeed">{posts.map((post) => { const link = post.map_url ?? post.url; const mapLink = link ? isMapLink(link) : false; return <article className="postCard" key={post.id}><header><UserAvatar user={{ id: post.author_id, name: post.author_name, avatar_color: post.avatar_color, avatar_key: post.avatar_key }} /><div><b>{post.author_name}</b><small>{post.created_at.replace('T', ' ').slice(0, 16)}</small></div><button aria-label="게시물 삭제" disabled={busyPost === post.id} onClick={async () => { if (confirm('게시물과 첨부 파일을 삭제할까요?')) try { setBusyPost(post.id); await boardApi.deletePost(post.id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : '게시물을 삭제하지 못했어요.'); } finally { setBusyPost(undefined); } }}><Trash2 size={16} /></button></header><small className={`postKind ${post.kind}`}>{kindLabel(post.kind)}</small>{post.title && <h2>{post.title}</h2>}{post.content && <p>{post.content}</p>}{link && <a className={`sharedUrl ${mapLink ? 'mapLink' : ''}`} href={link} target="_blank" rel="noreferrer">{mapLink ? <MapPinned size={15} /> : <ExternalLink size={15} />}{mapLink ? '지도에서 보기' : '링크 열기'}<small>{link}</small></a>}{post.attachments.length > 0 && <div className="attachments">{post.attachments.map((attachment) => attachment.content_type.startsWith('image/') ? <a href={boardApi.attachmentUrl(attachment.id)} target="_blank" rel="noreferrer" key={attachment.id}><img src={boardApi.attachmentUrl(attachment.id)} alt={attachment.file_name} /><small>{attachment.file_name}</small></a> : <a className="pdf" href={boardApi.attachmentUrl(attachment.id)} target="_blank" rel="noreferrer" key={attachment.id}><FileText /><span><b>{attachment.file_name}</b><small>{formatBytes(attachment.byte_size)}</small></span></a>)}</div>}<footer><span>여행 계획으로 연결</span><button disabled={busyPost === post.id || post.conversions.some((item) => item.target_type === 'planning')} onClick={() => convert(post)}><Plus size={14} />{busyPost === post.id ? '추가 중…' : '일정 후보로 추가'}</button></footer></article>; })}</div>
    {!loading && posts.length === 0 && <div className="boardEmpty"><Image /><b>아직 공유한 자료가 없어요.</b><span>첫 링크나 파일을 올려보세요.</span></div>}{hasMore && <button className="loadMore" disabled={loading} onClick={() => load(page + 1, true)}>{loading ? '불러오는 중…' : '이전 게시물 더 보기'}</button>}
  </section>;
}
